### ISSUE TITLE
Using the MEMFD VM option segfaults on up-to-date Debian and Ubuntu

### ISSUE THREAD

**Issue by lundgren87** [etascale/argodsm#124]
This is not resolved by setting `vm.overcommit_memory` to 1 and should be investigated.

This can be reproduced on GitHub actions using `ubuntu-latest`, as well as on Ubuntu 22.04 and up-to-date Debian.

**Comment by davidklaftenegger** [comment]
`vm.overcommit` should be set to `1`.

`0` is the default, which can have random ("heuristic") behaviour.

**Comment by lundgren87** [comment]
> `vm.overcommit_memory` should be set to `1`.
> 
> `0` is the default, which can have random ("heuristic") behaviour.

You're correct, posted the issue without double-checking the setup. Setting `vm.overcommit_memory` to `1` is what does _not_ resolve the issue.

**Comment by lundgren87** [comment]
The segfaulting code is the following lines:
https://github.com/etascale/argodsm/blob/2602a69da6f682696a4e012cd91d614671669ac0/src/virtual_memory/memfd.cpp#L57-L58

Removing `MAP_FIXED` causes initialization to pass, but has knock-on effects causing all other tests to fail as `ARGO_START` is no longer a guaranteed fixed value, in fact it can be (and locally is) different for each node. On further investigation, reducing the size of the ArgoDSM VM space from `0x600000000000-0x200000000000` to for example `0x500000000000-0x200000000000` ensures all tests pass.

I have double-checked that `/proc/sys/vm/overcommit_memory` is set to 1. I am not sure if there is any other possible restriction to the size?

**Comment by davidklaftenegger** [comment]
Please check and report the value of `sysctl kernel.randomize_va_space`. Maybe the problem goes away with `0` there.

It is somewhat weird that it only happens on certain systems though, and it should equally fail for the other VM implementations.

What kernel version is this on, and can you (easily) check against some older kernel as well?

**Comment by lundgren87** [comment]
Disabling ASLR does not seem to fix the problem on my end (someone else feel free to test). Tested on kernel versions 5.15.0 and 5.10.0. I don't have easy access to anything significantly different from this.

**Comment by davidklaftenegger** [comment]
Please also check the output of `dmesg` after the process has crashed.

If that doesn't explain anything, can you check what the memory mappings look like [1] right before the failing call, and possibly even before the memfd syscall?
I think this should only fail when there is a conflicting mapping, but it is possible some recent kernel introduced some other limits as well.

As a workaround, I think reducing the maximum available memory size is reasonable (but does not fix the bug).
Who needs 64TB anyway?


[1] e.g. by using https://linux.die.net/man/1/pmap or by inspecting `/proc/self/maps` from the code. I have not checked whether easier ways exist.

**Comment by lundgren87** [comment]
When inspecting the memory mappings of a running ArgoDSM process using `SHM`, the default value of `ARGO_END` appears too large and intrudes on the mapping of the heap among other things.

```
5562b64b2000-5562b64b3000 rw-p 0009c000 103:08 8528772                   /home/sven/git/argodsm/build/bin/mpi/barrierTests
5562b6d06000-5562b7108000 rw-p 00000000 00:00 0                          [heap]
7fe8a0000000-7fe8a0021000 rw-p 00000000 00:00 0 
```

The mapping of the heap appears to be in this approximate region for each process I have inspected on my system. As a result the initial anonymous mapping below fails using MEMFD:
https://github.com/etascale/argodsm/blob/605645ae17707b36d1be736fcc9b525997052f02/src/virtual_memory/memfd.cpp#L58

This mapping succeeds on my system if `ARGO_END` is set to `0x550000000000l`, while `0x560000000000l` occasionally fails. These results are similar to those obtained earlier.
