### ISSUE TITLE
Insufficient linking with librt

### ISSUE THREAD

**Issue by lundgren87** [etascale/argodsm#16]
### Issue
Compiling and linking external projects with ArgoDSM produces the following error.
`undefined reference to symbol 'shm_unlink@@GLIBC_2.2.5'`
`//lib/x86_64-linux-gnu/librt.so.1: error adding symbols: DSO missing from command line`

shm_open/shm_unlink [requires linking with librt](http://man7.org/linux/man-pages/man3/shm_open.3.html) (-lrt). This is currently done on src/CMakeLists.txt line 37 through `set(vm_libs rt)` but this does not appear to be sufficient when the ArgoDSM libraries are linked from an external project.

### Steps to reproduce

1. Follow the ArgoDSM [quickstart guide](https://etascale.github.io/argodsm/) to build ArgoDSM.
2. Run make install.
3. Follow the ArgoDSM [tutorial](https://etascale.github.io/argodsm/tutorial.html) to compile and link argo_example.cpp with the ArgoDSM libraries, reproducing the error.
4. Link with librt by adding -lrt to the final line in order to successfully compile. (`-largo -largobackend-mpi -lrt`)

Tested with gcc/g++ (mpicc/mpic++) versions 6.5.0 and 7.3.0.

**Comment by davidklaftenegger** [comment]
You are correct, we did not experience this issue as CMake makes it go away when building additional programs within our project tree, but it of course does not work for external projects. I will find a solution for this, but will require some time for testing it.
