### ISSUE TITLE
Unify the definition of page size

### ISSUE THREAD

**Issue by lundgren87** [etascale/argodsm#49]
Related to the discussion in:
https://github.com/etascale/argodsm/pull/45#discussion_r577999626

ArgoDSM page size should be defined in one module instead of appearing as separate `static const` definitions in multiple modules, and retrieved from there where needed throughout the system.

**Comment by lundgren87** [comment]
Should this issue also deal with the hardcoded `CACHELINE` value, which I am sure changing to anything besides 1L has not worked very well for a long time (and definitely does not work with allocation policies)?

I would suggest removing it entirely, or possibly baking it in to the future unified definition of page size. It should now serve very little purpose with the introduction of allocation policies, prefetching and a new write buffer.

**Comment by lundgren87** [comment]
I have opened a new issue regarding `CACHELINE` so that #128 can resolve this issue.

**Comment by kostis** [comment]
Closing this issue due to merging #125.
The `CACHELINE` issues will be discussed and/or resolved in #128.
